[package]
name = "OKXMarketData"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "0.18", features = ["native-tls"] }
serde_json = "1.0"
futures-util = "0.3"